### ISSUE TITLE
Ticket Epic

### ISSUE THREAD

**Issue by yohagos** [yohagos/midgard-ng#5]
Create Tickets
- [ ] Forms
- [ ] Services
-----------------------------------------------------------

Modify Tickets
- [ ] Forms
- [ ] Services
-----------------------------------------------------------

Search for Tickets
- [ ] Depending on priorities
- [ ] Depending on categories
- [ ] Depending on Owner
